# Generated by Django 4.1.10 on 2023-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_team", models.CharField(max_length=255)),
                ("home_score", models.CharField(max_length=255)),
            ],
        ),
    ]
