# Generated by Django 4.1.10 on 2023-08-06 10:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FootballLeague",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("league_id_last", models.IntegerField()),
                ("league_id_prev", models.IntegerField()),
            ],
            options={
                "db_table": "football_league",
            },
        ),
        migrations.CreateModel(
            name="FootballMatch",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("league_id", models.IntegerField()),
                ("match_id", models.IntegerField()),
                ("round_id", models.IntegerField()),
                ("game_week", models.IntegerField()),
                ("home_goals", djongo.models.fields.JSONField()),
                ("away_goals", djongo.models.fields.JSONField()),
                ("team_a_yellow_cards", models.IntegerField()),
                ("team_b_yellow_cards", models.IntegerField()),
                ("team_a_red_cards", models.IntegerField()),
                ("team_b_red_cards", models.IntegerField()),
                ("stadium_name", models.CharField(max_length=100)),
                ("team_a_dangerous_attacks", models.IntegerField()),
                ("team_b_dangerous_attacks", models.IntegerField()),
                ("team_a_attacks", models.IntegerField()),
                ("team_b_attacks", models.IntegerField()),
                ("team_a_xg", models.FloatField()),
                ("team_b_xg", models.FloatField()),
                ("team_a_penalties_won", models.IntegerField()),
                ("team_b_penalties_won", models.IntegerField()),
                ("team_a_penalty_goals", models.IntegerField()),
                ("team_b_penalty_goals", models.IntegerField()),
                ("team_a_penalty_missed", models.IntegerField()),
                ("team_b_penalty_missed", models.IntegerField()),
                ("team_a_throwins", models.IntegerField()),
                ("team_b_throwins", models.IntegerField()),
                ("team_a_freekicks", models.IntegerField()),
                ("team_b_freekicks", models.IntegerField()),
                ("team_a_goalkicks", models.IntegerField()),
                ("team_b_goalkicks", models.IntegerField()),
                ("date_unix", models.CharField(max_length=100)),
                ("date_unix_thai", models.CharField(max_length=100)),
                ("time_unix", models.CharField(max_length=100)),
                ("home_id", models.IntegerField()),
                ("away_id", models.IntegerField()),
                ("season", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("home_goal_count", models.IntegerField()),
                ("away_goal_count", models.IntegerField()),
                ("winning_team", models.CharField(max_length=100)),
                ("home_name", models.CharField(max_length=100)),
                ("away_name", models.CharField(max_length=100)),
                ("home_image", models.CharField(max_length=100)),
                ("away_image", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "football_match",
            },
        ),
        migrations.CreateModel(
            name="FootballTeams",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "football_teams",
            },
        ),
        migrations.CreateModel(
            name="FootballTeamStat",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "football_teams_stat",
            },
        ),
    ]
