# Generated by Django 4.1.10 on 2023-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballresults", "0002_footballmatch_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballmatch",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
