# Generated by Django 4.1.10 on 2023-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footballresults", "0003_alter_footballmatch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footballmatch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
